name: Ruby

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  KEY_ENCRYPTION_SALT: "1234567890"
  HYPATIA_SERVER_URL: "https://www.example.com"
  HYPATIA_AUTH_KEY: "1234567890"
  FACT_CHECK_INSIGHTS_HOST: "factcheckinsights.org"
  MEDIA_VAULT_HOST: "vault.factcheckinsights.org"
  AUTH_BASE_HOST: "factcheckinsights.org"
  MAIL_DOMAIN: "factcheckinsights.org"
  MAILGUN_API_KEY: "1234567890"
  PUBLIC_LINK_HOST: "public.factcheckinsights.org"
  RECAPTCHA_SITE_KEY: "1234567890"
  RECAPTCHA_PROJECT_ID: "1234567890"
  OLLAMA_URL: "https://www.example.com"
  OLLAMA_PASSWORD: "1234567890"
  FACTCHECK_TOOLS_API_KEY: "1234567890"
  CHROME_EXTENSION_ID: "1234567890"
  VIPS_WARNING: "0"
  USE_S3_DEV_TEST: "false"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install system packages
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.7
        bundler-cache: true
    - name: Lint with Rubocop
      run: bundle exec rubocop
  tests:
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:
    - uses: actions/checkout@v4
    - uses: FedericoCarboni/setup-ffmpeg@v2
    - name: Install system packages
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev libvips
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.7
        bundler-cache: true
    - name: Setup database
      run: bundle exec rails db:setup
    - name: Precompile assets
      run: bundle exec rake assets:precompile
    - name: Run tests
      run: bundle exec rails test
